//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPrakApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Autos()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int AutoId { get; set; }
        public string AutoMark { get; set; }
        public string AutoModel { get; set; }
        public int AutoMileage { get; set; }
        public string AutoCityLocation { get; set; }
        public string AutoEngineDisplacement { get; set; }
        public int AutoLS { get; set; }
        public string AutoGearbox { get; set; }
        public string AutoFuelType { get; set; }
        public string AutoDriveType { get; set; }
        public decimal AutoPrice { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
