//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfPrakApp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int EmployeeId { get; set; }
        public int AutoId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Autos Autos { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
